name = "WrapperSimplification"
uuid = "6fcb37a8-74b4-44d4-930c-20316af4e970"
authors = ["Lyndon White"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
